# Generated by Django 4.2.7 on 2024-01-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rover',
            fields=[
                ('rover_id', models.AutoField(primary_key=True, serialize=False)),
                ('rover_name', models.CharField(max_length=20)),
                ('rover_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='rovers_images')),
                ('is_available', models.BooleanField(default=True)),
                ('charge', models.PositiveIntegerField(default=0)),
                ('location_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Марсоход',
                'verbose_name_plural': 'Марсоходы',
            },
        ),
        migrations.CreateModel(
            name='Using',
            fields=[
                ('using_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('rover', models.ForeignKey(db_column='rover_id', on_delete=django.db.models.deletion.CASCADE, related_name='usings', to='rovers.rover')),
            ],
            options={
                'verbose_name': 'Аренду',
                'verbose_name_plural': 'Аренды',
            },
        ),
    ]
