# Generated by Django 4.2.7 on 2024-01-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rover',
            name='equipment',
            field=models.TextField(null=True),
        ),
    ]
