# Generated by Django 4.2.7 on 2024-01-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0003_rover_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rover',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rover',
            name='speed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rover',
            name='rover_number',
            field=models.CharField(max_length=10),
        ),
    ]
