# Generated by Django 4.2.7 on 2024-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0004_rover_mileage_rover_speed_alter_rover_rover_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rover',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
