# Generated by Django 4.2.7 on 2024-01-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0005_rover_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='using',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
