# Generated by Django 4.2.7 on 2024-01-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0006_alter_using_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='using',
            old_name='rover',
            new_name='rover_id',
        ),
        migrations.RenameField(
            model_name='using',
            old_name='user',
            new_name='user_id',
        ),
    ]
