# Generated by Django 4.2.7 on 2024-01-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0007_rename_rover_using_rover_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='using',
            old_name='rover_id',
            new_name='rover',
        ),
        migrations.RenameField(
            model_name='using',
            old_name='user_id',
            new_name='user',
        ),
    ]
